### ISSUE TITLE
Typo in bidirectional encoder?

### ISSUE THREAD

**Issue by ghost** [ematvey/tensorflow-seq2seq-tutorials#1]
Apologies if I'm misunderstanding something here. In `model_new.py`, the bidirectional encoder outputs a concatenation of the forward output with itself. Should this be a concatenation of the forward and backward outputs?
([See line 176](https://github.com/ematvey/tensorflow-seq2seq-tutorials/blob/master/model_new.py#L176))

**Comment by ematvey** [comment]
It is a typo. Thanks for noticing! Fixed it.
