### ISSUE TITLE
A bug in the second model?

### ISSUE THREAD

**Issue by Dr-Corgi** [ematvey/tensorflow-seq2seq-tutorials#10]
The codes in the article  **Advanced dynamic seq2seq with TensorFlow** (In [13])
`
encoder_outputs = tf.concat((encoder_fw_outputs, encoder_fw_outputs), 2)
`
should be
`
encoder_outputs = tf.concat((encoder_fw_outputs, encoder_bw_outputs), 2)
`
isn't it?

**Comment by ematvey** [comment]
Yes, fixed it, thanks. It didn't affect anything, concatenated encoder_outputs are not used anywhere. It would if you implement attention.
