### ISSUE TITLE
Correct Way Prepare Data?

### ISSUE THREAD

**Issue by lucasjinreal** [ematvey/tensorflow-seq2seq-tutorials#13]
Hi, thks for this wonderful tutorial, in `new_seq2seq.py` seems index 0 and 1 was placed by EOS and PAD, so should I prepare my data start from 2 rather than from 0. For instance:

if I have these corpus:
```
Alice saw a big rabbit in forest.
```
then should I change vocab_int_map into this?

```
{'Alice': 2, 'saw': 3, 'a': 4,...}
```

so that all vocab index will not have 0 and 1.
wish get your help, cause I trained the model but not sure how to deal with this problem. thnks in advance!

**Comment by ematvey** [comment]
Yep, first couple of vocab IDs are reserved for tokens. Check out how `train_on_copy_task` is called in tutorial 3.

**Comment by lucasjinreal** [comment]
tnks, mat
