### ISSUE TITLE
Links broken

### ISSUE THREAD

**Issue by Restioson** [ematvey/tensorflow-seq2seq-tutorials#16]
Many links to this repo in the notebooks are broken, e.g [this link](https://render.githubusercontent.com/view/3-seq2seq-native-new.ipynb) returns `Unknown type`.

**Comment by ematvey** [comment]
Are you getting this from local notebook? Links are meant to work when viewing from github.

**Comment by Restioson** [comment]
I am viewing this from your online repo. Thanks for the explanation, by the way :)

**Comment by Restioson** [comment]
Right now I am having issues loading the notebook. I am sure that this is not related to you in any way though. It was working previously

**Comment by ematvey** [comment]
I'm having them too from time to time. I checked all links (well, probably), they seem to work.
