### ISSUE TITLE
new changes in tensorflow

### ISSUE THREAD

**Issue by ehsanasgari** [ematvey/tensorflow-seq2seq-tutorials#17]
Hi there,

Thank you for the great work! I was wondering if you figured it out how to change the code to run in tf 1.1?

**Comment by Blockost** [comment]
I would also be interested in seeing your code modified with Tensorflow 1.1 API

**Comment by ematvey** [comment]
I switched from TF, so not sure how soon I will get to it. If anyone wants so submit a PR, will be happy to merge.

**Comment by Blockost** [comment]
Did you switch to PyTorch as you mentioned in a previous issue? 

I'll figure this out and submit a PR if my code is worthy :)

**Comment by ematvey** [comment]
@Blockost Would be happy to merge your PR!
