### ISSUE TITLE
Multilayered Bidirectional seq2seq

### ISSUE THREAD

**Issue by adakum** [ematvey/tensorflow-seq2seq-tutorials#19]
Hi ,
Thanks a lot for creating this tutorial. 
Would appreciate if u can help me modify this code to make it multilayered bi-directional seq2seq. 
I could not find any function in tf.contrib.seq2seq (version 1.0) to make it multilayered.

**Comment by ematvey** [comment]
If you want to concatenate fw/bw states after each layer, check this out: https://www.tensorflow.org/api_docs/python/tf/contrib/rnn/stack_bidirectional_rnn

**Comment by adakum** [comment]
I had a look at the stack_bidirectional_rnn. But I don't see the argument for the num_layers ?  
I am little confused. Without num_layers how it will decide how many layers to stack ?

**Comment by ematvey** [comment]
You should pass multiple cells as `cells_fw` and `cells_fw`, one per layer. This is based on the description, I did not use it.

**Comment by adakum** [comment]
Got it. But that function is not in TF 1.0. Any idea for TF 1.0 ?

**Comment by ematvey** [comment]
Same thing, but manually concatenate/stack layers in a for loop.

**Comment by adakum** [comment]
Hi, Sorry for badgering but I would really appreciate if you can respond to this related post by me 
https://stackoverflow.com/questions/44498771/multilayered-encoder-output-state-to-multilayered-decoder-in-seq2seq-model
