### ISSUE TITLE
[Suggestion] PAD added twice

### ISSUE THREAD

**Issue by ghost** [ematvey/tensorflow-seq2seq-tutorials#2]
Your first tutorial has this code snippet:

    decoder_targets_, _ = helpers.batch(
        [(sequence) + [EOS] + [PAD] * 2 for sequence in batch]
    )
    decoder_inputs_, _ = helpers.batch(
        [[EOS] + (sequence) + [PAD] * 2 for sequence in batch]
    )

I'm opening this issue to suggest that you add an explanation for why you append `PAD` twice, if you have time, since I don't understand this part myself. Thanks for these tutorials; I'm finding them very helpful!

**Comment by ematvey** [comment]
This bit was meant to illustrate that decoder rollout is somewhat arbitrary and is controlled by us. This is probably not very important implementation detail given scope of tutorial 1. Dropped it.
