### ISSUE TITLE
Potential bug of the dynamic_decoder

### ISSUE THREAD

**Issue by ghost** [ematvey/tensorflow-seq2seq-tutorials#20]
If I set the `num_units` of the cell in decoder as the twice as the one in encoder (just like what the tutorial does), everything goes well. But If I set, say, both of the encoder and decoder's cell have the same `num_units`. Then the incompatible shape error occurs. Is it related to the `LSTM` issue? Thanks.

**Comment by ematvey** [comment]
Not a bug. 
This is because encoder is bidirectional, and encoder state is passed to decoder as-is. You can instead put a linear layer between encoder final state and decoder initial state and use whatever dimensionality you like.

**Comment by ghost** [comment]
@ematvey  Oh yes, sorry I made a stupid mistake.

**Comment by rylanchiu** [comment]
But why did you use the [rnn output](https://github.com/ematvey/tensorflow-seq2seq-tutorials/blob/master/model_new.py#L176) for attention? As I know, the `query` and `keys` should be the hidden state of the encoder. Please correct me if I made a mistake again... TIA!
