### ISSUE TITLE
module 'tensorflow.contrib.seq2seq' has no attribute 'prepare_attention'

### ISSUE THREAD

**Issue by yangshao** [ematvey/tensorflow-seq2seq-tutorials#24]
I'm trying the 3rd tutorial, and got error: module 'tensorflow.contrib.seq2seq' has no attribute 'prepare_attention'. The tensorflow version of mine is 1.1.0. How to I change the code for the 1.1.0 version? Thanks.

**Comment by ematvey** [comment]
FYI, Google just released their own tutorials for NMT: https://github.com/tensorflow/nmt

**Comment by ematvey** [comment]
Deprecating 3 tutorial as it doesn't provide any useful intuition, just shows API use.
