### ISSUE TITLE
Update tutorial #3 to match new TF seq2seq API

### ISSUE THREAD

**Issue by ematvey** [ematvey/tensorflow-seq2seq-tutorials#8]
Whenever it is released.

**Comment by Jiakui** [comment]
it seems that the seq2seq API changes very frequently. I tried to run tutorial #3 under tensorflow 1.0.0 and it didn't run, but 1.0.0-alpha1 worked for me a couple of days ago.

**Comment by byangderek** [comment]
> it seems that the seq2seq API changes very frequently. 

It's true.

At the time I wrote this, tutorial 3 works on pip-installed tensorflow, but doesn't work on compiled-from-source tensorflow. (both latest and show version 1.0.1)

However, Google's [seq2seq](https://github.com/google/seq2seq) repo works on both. (at least for the [rnn_encoder_test](https://github.com/google/seq2seq/blob/master/seq2seq/test/rnn_encoder_test.py))

**Comment by ematvey** [comment]
After they stabilize API a bit I'll update tutorial 3. It also might not be necessary if they release their own sufficienctly clear tutorials, althout at this time they went with YAML configs instead of code examples (https://google.github.io/seq2seq/nmt/).

**Comment by byangderek** [comment]
Many thanks to the pytorch seq2seq example! Seems like pytorch codes are more friendly to beginners.

**Comment by rahulraju93** [comment]
Hello @ematvey ,
                             Did you get a chance to update #3? Also do you think that #3 is better than #2?
Thank you
